### ISSUE TITLE
Travis test matrix updates

### ISSUE THREAD

**Issue by dkirkby** [astropy/package-template#271] opened 2017-10-03 00:02 UTC
The current travis config has a few issues:

```
env: PYTHON_VERSION=2.7 ASTROPY_VERSION=development
```
This combination is no longer supported (which is related to #264).

```
env: NUMPY_VERSION=prerelease
```
This combination results in `Prerelease for numpy is not available, stopping test`.

```
env: PYTHON_VERSION=2.7 NUMPY_VERSION=1.7
```
For reasons that I don't understand, this combination never installs numpy 1.7 and instead runs with numpy 1.13.

**Comment by bsipocz** [comment] 2017-10-03 00:16
Thanks @dkirkby for the issue. I'm in the process of updating the matrix, but in the meantime the summary:

1) yes, astropy dev is no longer support 2.7, so that job will be removed. I also plan to open at some point an issue for all repositories on github that still uses that combination. Possibly it can be done in an automated PR but that needs some more time to get work properly.

2) Yes, while the comment is new, that behaviour was always the same in ci-helpers. See [readme](https://github.com/astropy/ci-helpers/blob/master/README.md) or https://github.com/astropy/ci-helpers/issues/239#issuecomment-332807821

3) astropy stable is not compatible with numpy 1.7, so the conda install falls back on pip install, but that automatically updates numpy to a version that compatible with astropy stable. This is currently a bug in ci-helpers, and is being worked on: https://github.com/astropy/ci-helpers/issues/241
Actually it would be nice to get some imput on the desired behaviour here, presumably an errored install is preferred rather than silently updating the mandatory dependencies?

**Comment by dkirkby** [comment] 2017-10-03 00:21
> Actually it would be nice to get some imput on the desired behaviour here

As far as the test matrix is concerned, dropping numpy 1.7 sounds like the solution.  More generally, it would be helpful if the conda install fails if it detects an incompatible dependency, rather than falling back to a pip install (or are there situations when this behavior is needed?)

**Comment by bsipocz** [comment] 2017-10-03 00:27
As a workaround for the moment, you can use ``PIP_FALLBACK=false`` to switch off the pip fallback. We are considering to also changing the default to this behaviour as it sadly caused many problems while solved only a few.

**Comment by bsipocz** [comment] 2017-10-03 17:22
OK, so master as been updated and cleaned up by the trivially failing jobs. For the pip fallback there are issues open already in ci-helpers, so I'm closing this here.

Please reopen if you think otherwise, and also feel free to open issues for any inconsistencies/bugs in ci-helpers or here.

**Closed by bsipocz** 2017-10-03 17:22 UTC
Labels: template

**Comment by dkirkby** [comment] 2017-10-03 17:42
Two possibly related issues:
 - NUMPY_VERSION=stable is resolving to numpy 1.13 but (until recently) the matrix only covers up to 1.11
 - ASTROPY_VERSION=stable is resolving to 2.0.2, for which conda install fails so it always falls back to a pip install.  Shouldn't the stable version always be conda installable?

**Comment by bsipocz** [comment] 2017-10-03 18:29
Thanks @dkirkby for pointing these out:

- Indeed the 2.0.2 version on the ``default`` conda channel is somehow broken. This is beyond our control, and I have opened an upstream issue for it: https://github.com/conda/conda/issues/6069
It only affects the linux builds, and the version on the ``conda-forge`` channel can be installed without issues.

I'm adding one more build for np 1.12 to the matrix. we were talking about maybe adding these as stable-1, stable-2, etc, but I'm still not sure that's a good idea in practice.

**Comment by dkirkby** [comment] 2017-10-03 18:45
I am still stuck with one mystery in my travis tests: an affiliated pkg (specsim) is failing on:
```
env: SETUP_CMD='build_docs -w'
```
when it pip installs another affiliated pkg (speclite).  Here is the [log](https://travis-ci.org/desihub/specsim/jobs/282525384).  The actual error is an infinite recursion triggered by:
```
      File "/tmp/pip-build-co8y23n2/speclite/setup.py", line 80, in <module>
        cmdclassd = register_commands(PACKAGENAME, VERSION, RELEASE)
      File "/tmp/pip-build-co8y23n2/speclite/.eggs/astropy_helpers-1.0.7-py3.6.egg/astropy_helpers/setup_helpers.py", line 281, in register_commands
        from .commands.build_sphinx import AstropyBuildSphinx, AstropyBuildDocs
      File "/tmp/pip-build-co8y23n2/speclite/.eggs/astropy_helpers-1.0.7-py3.6.egg/astropy_helpers/commands/build_sphinx.py", line 14, in <module>
```
However, the `build_doc -w` test for speclite itself passes with [no problem](https://travis-ci.org/dkirkby/speclite) and all other specsim tests that install speclite have [no problems](https://travis-ci.org/desihub/specsim/jobs/282525382).  Do you see anything obvious here?

**Comment by bsipocz** [comment] 2017-10-03 18:49
Your ``astropy-helpers`` is very old. To be able to use sphinx >1.6, you'll need to have the astropy-helpers >=2.0

We do automated helpers update PRs for affiliated and a few other packages that opted in. I'm happy to add any of your packages to that list for future updates.

**Comment by dkirkby** [comment] 2017-10-03 19:00
I believe I am using astropy-helpers v2.0.1, so I don't know why v1.0.7 appears in that path!
```
% git clone git@github.com:dkirkby/speclite.git
% cd speclite
% python setup.py install
Initializing astropy_helpers submodule with: `git submodule update --init -- astropy_helpers`
...
% cd astropy_helpers
% git status
HEAD detached at 14ca346
```
This is the correct [commit id for v2.0.1](https://github.com/astropy/astropy-helpers/commit/14ca346b0da3e92e65bdc398cc8f726cbd7be57d).

Perhaps the `git submodule update` command is not called when the speclite dependency is (pip) installed for the `build_doc` target?

**Comment by dkirkby** [comment] 2017-10-03 19:01
Note that the `build_doc` (and all other) tests work fine for speclite itself.  The only failure is when speclite is installed as part of the `build_doc` test for a package (specsim) that depends on speclite.

**Comment by dkirkby** [comment] 2017-10-03 19:05
> I'm happy to add any of your packages to that list for future updates.

Yes please!  The packages are:
 - https://github.com/desihub/specsim
 - https://github.com/dkirkby/speclite

**Comment by bsipocz** [comment] 2017-10-03 19:06
Hmm this is odd, I'll try to reproduce the failure locally and will comment back on it.

**Comment by bsipocz** [comment] 2017-10-03 19:48
@dkirkby - while I'm not yet sure why that 1.0.7 version number showed up in there, I hope I've found the issue. It looks like that while the helpers submodule got updated, ``ah_bootstrap`` not. I've opened PRs to those repos.

**Comment by dkirkby** [comment] 2017-10-03 21:35
Thanks @bsipocz!
